# Generated by Django 4.1 on 2023-02-13 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myntraapp', '0008_bagmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bagmodel',
        ),
    ]
