# Generated by Django 4.1 on 2023-02-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myntraapp', '0010_buy'),
    ]

    operations = [
        migrations.CreateModel(
            name='customercardpay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardname', models.CharField(max_length=30)),
                ('cardnumber', models.CharField(max_length=30)),
                ('cardexpiry', models.CharField(max_length=30)),
                ('securitycode', models.CharField(max_length=30)),
            ],
        ),
    ]
