# Generated by Django 4.1 on 2023-02-15 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myntraapp', '0011_customercardpay'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customercardpay',
            new_name='customercard',
        ),
    ]
