# Generated by Django 4.1 on 2023-02-16 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myntraapp', '0013_customerlocationmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customerlocationmodel',
        ),
    ]
