# Generated by Django 4.1 on 2023-02-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myntraapp', '0014_delete_customerlocationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuploadmodels',
            name='shopid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
