# Generated by Django 4.1 on 2023-02-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myntraapp', '0017_remove_shopuploadmodels_shopname'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuploadmodels',
            name='shopname',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
