# Generated by Django 4.1 on 2023-02-17 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myntraapp', '0019_remove_shopuploadmodels_shopname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopuploadmodels',
            old_name='shopid',
            new_name='shopuserid',
        ),
    ]
