# Generated by Django 4.1 on 2023-02-17 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myntraapp', '0020_rename_shopid_shopuploadmodels_shopuserid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopuploadmodels',
            old_name='shopuserid',
            new_name='shopid',
        ),
    ]
