# Generated by Django 4.1 on 2023-02-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myntraapp', '0021_rename_shopuserid_shopuploadmodels_shopid'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuploadmodels',
            name='userid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
