# Generated by Django 4.1 on 2023-02-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myntraapp', '0022_shopuploadmodels_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='userid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
