# Generated by Django 4.1 on 2023-02-21 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myntraapp', '0027_shopnotification_usernotification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopnotification',
            old_name='time',
            new_name='shopnottime',
        ),
        migrations.RenameField(
            model_name='usernotification',
            old_name='time',
            new_name='usernottime',
        ),
    ]
