# Generated by Django 4.1 on 2023-02-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myntraapp', '0028_rename_time_shopnotification_shopnottime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopnotification',
            name='shopnottime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='usernottime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
